name: Release Label

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled, ready_for_review]

permissions:
  pull-requests: read

jobs:
  release-label:
    name: Require release label
    runs-on: ubuntu-latest
    steps:
      - name: Release label check disabled
        run: echo "Release label check temporarily disabled."
